openapi: 3.0.0
info:
  title: Organizations API
  version: 1.0.0
  description: API endpoints for managing organizations

paths:
  /api/v1/organizations:
    get:
      summary: List organizations
      description: Returns a list of organizations. For employees, returns organizations where they are employed. For owners, returns organizations they own.
      tags:
        - Organizations
      responses:
        '200':
          description: List of organizations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
    
    post:
      summary: Create a new organization
      description: Creates a new organization. Only users with 'owner' role can create organizations.
      tags:
        - Organizations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name of the organization
                description:
                  type: string
                  description: Description of the organization
                established_at:
                  type: string
                  format: date
                  description: Date when organization was established
      responses:
        '201':
          description: Organization created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity (validation failed)

  /api/v1/organizations/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Organization ID
    
    get:
      summary: Get organization details
      description: Returns details of a specific organization. User must be owner or employed in the organization.
      tags:
        - Organizations
      responses:
        '200':
          description: Organization details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Organization not found
    
    put:
      summary: Update organization
      description: Updates an organization. Only organization owner can perform this action.
      tags:
        - Organizations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the organization
                description:
                  type: string
                  description: Description of the organization
                established_at:
                  type: string
                  format: date
                  description: Date when organization was established
      responses:
        '200':
          description: Organization updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Organization not found
        '422':
          description: Unprocessable Entity (validation failed)
    
    delete:
      summary: Delete organization
      description: Deletes an organization. Only organization owner can perform this action.
      tags:
        - Organizations
      responses:
        '204':
          description: Organization deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Organization not found

components:
  schemas:
    Organization:
      type: object
      properties:
        id:
          type: integer
          description: Organization ID
        name:
          type: string
          description: Name of the organization
        description:
          type: string
          description: Description of the organization
        established_at:
          type: string
          format: date
          description: Date when organization was established
        owner_id:
          type: integer
          description: ID of the organization owner
        created_at:
          type: string
          format: date-time
          description: Timestamp when the organization was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the organization was last updated 